name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - uses: volta-cli/action@v1

      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-yarn-cache-

      - name: yarn install
        run: yarn install --frozen-lockfile --ignore-engines --non-interactive --production=false

      - run: yarn test
